services:
  tickr:
    image: hoffmanju/tickr:latest
    container_name: tickr
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000/tcp
    # env_file:
    #   - .env
    # environment:
    #   - TICKR_DATABASE=data/tickr.db
    #   - TICKR_RATE_LIMIT_REQUESTS=100
    #   - TICKR_MAX_SSE_CLIENTS=10
    #   - TICKR_CORS_ORIGINS=https://app.example.com,https://admin.example.com
    volumes:
      - ./data:/app/data
